# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
  pull_request:
  workflow_dispatch: # Allow running manually from web UI

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Set up JDK 17
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Gradle Info
        run: ./gradlew -version

      - name: Build with Gradle
        run: ./gradlew build
